### ISSUE TITLE
Looking for a DLL

### ISSUE THREAD

**Issue by abu-irrational** [Wiladams/svgandme#1]
I'd like to use svgandme's logic as a DLL.
This DLL should just contain the SVGDocument, SVGDrawingContext classes and little else.

But I see that exporting a C++ class into a DLL is a portability nightmare, unless they are built like Blend2d, i.e. as I understand it, exported as C functions and then 'wrapped' into C++ classes at the 'import side'.

Could you tell me how to create this DLL?

One last question: how should the FontHandler thing work on Linux/Mac? Should a small set of font files be included in svgandme?

**Comment by Wiladams** [comment]
svgandme is "header only", meaning, all the code is in '.h' files, so no need for a .dll, or any other 'library' mechanism.  Just include 'svg.h' and you're done.  The one exception is the base64.cpp, which you also need to compile, but there's no reason that can't also just be a headed, so I'll change that.

FontHandler, yah, there's some challenges there when you just say "loadDefaultFonts", but you can specify a specific directory, and even a set of files to load.  'loadDefault...' should probably be some #ifdef code that does the platform specific right thing.

**Comment by Wiladams** [comment]
I have removed or shifted any items that would require a .dll.  The code should be pure 'header only' at this point.

**Comment by Wiladams** [comment]
closed as the code is header only at this point
