### ISSUE TITLE
Minimal command line for building svgandme

### ISSUE THREAD

**Issue by abu-irrational** [Wiladams/svgandme#2]
Hi William, 
I successfully compiled and run all your small apps (svgimage.exe .... ), but 
I'm having big problems integrating "svgandme" as "header-only" into my app.
I took inspiration from some parts of "svgimage.cpp", but it produces a crash already in the parsing phase. 
   ....
   SVGGraphicsElement::loadCompoundNode == UNKNOWN ==> 'style'
   then crash !

The most incredible thing is that I can compile/link even without including "base64.cpp"! 
I would expect a linker error like "missing base64_decode()", but instead the linker doesn't give me any errors... then it crashes when I load an svg file.
The only changes I made in your code were to replace #include "blend2/blend2d.h" with "#include <blend2d.h>"
, and then point to a 'my' directory containing all blend2d include-files.
I therefore suspect that there are some major conflicts already in the compilation phase. I honestly didn't understand all the compilation options used in MSVC.

I should probably start again from "svgimage.cpp", and for this reason I ask you if you can provide me with a minimal DOS 'command-line' for its compilation.

**Comment by Wiladams** [comment]
ok.  And can you give me an example of your .svg?  But, the most important thing, that might not be obvious, is you MUST have a line in your code that looks like this.

using namespace waavs;

// Create one of these first, so factory constructor will run
SVGFactory gSVG;

The fact that it could not find the 'style' element, which is pretty fundamental, means the factory was not setup, so it doesn't have any registrations on how to parse the elements.

**Comment by Wiladams** [comment]
The README.md file in the testy directory has an example command line.  Maybe you can try that?

**Comment by abu-irrational** [comment]
Thank you William, I forgot to initialize

  SVGFactory gSVG;

Now it works.

**Comment by Oldes** [comment]
@Wiladams the [README.md](https://github.com/Wiladams/svgandme/blob/main/testy/README.md) file in the `testy` folder looks outdated as there is no `core` directory in your repository.

**Comment by Wiladams** [comment]
I have updated the readme to be current.  I believe we’ve resolved all issues here.
